### ISSUE TITLE
Fails to build with libosmium 2.11.0

### ISSUE THREAD

**Issue by sebastic** [osmcode/pyosmium#24]
pyosmium 2.10.2 fails to build with libosmium 2.11.0:
```
building 'osmium.io' extension
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -g -O2 -fdebug-prefix-map=/build/pyosmium-2.10.2=. -specs=/usr/share/dpkg/no-pie-compile.specs -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include -I/usr/include/python2.7 -c lib/io.cc -o build/temp.linux-x86_64-2.7/lib/io.o -std=c++11 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64
cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++
In file included from lib/io.cc:5:0:
lib/osm.cc: In function 'void init_module__osm()':
lib/osm.cc:173:111: error: no matching function for call to 'boost::python::class_<osmium::NodeRefList, boost::noncopyable_::noncopyable>::def(const char [12], <unresolved overloaded function type>, boost::python::return_value_policy<boost::python::reference_existing_object>)'
         .def("__getitem__", &osmium::NodeRefList::operator[], return_value_policy<reference_existing_object>())
                                                                                                               ^
In file included from /usr/include/boost/python.hpp:18:0,
                 from lib/io.cc:1:
/usr/include/boost/python/class.hpp:223:11: note: candidate: template<class Derived> boost::python::class_<T, X1, X2, X3>::self& boost::python::class_<T, X1, X2, X3>::def(const boost::python::def_visitor<Derived>&) [with Derived = Derived; W = osmium::NodeRefList; X1 = boost::noncopyable_::noncopyable; X2 = boost::python::detail::not_specified; X3 = boost::python::detail::not_specified]
     self& def(def_visitor<Derived> const& visitor)
           ^~~
/usr/include/boost/python/class.hpp:223:11: note:   template argument deduction/substitution failed:
In file included from lib/io.cc:5:0:
lib/osm.cc:173:111: note:   mismatched types 'const boost::python::def_visitor<U>' and 'const char [12]'
         .def("__getitem__", &osmium::NodeRefList::operator[], return_value_policy<reference_existing_object>())
                                                                                                               ^
In file included from /usr/include/boost/python.hpp:18:0,
                 from lib/io.cc:1:
/usr/include/boost/python/class.hpp:233:11: note: candidate: template<class F> boost::python::class_<T, X1, X2, X3>::self& boost::python::class_<T, X1, X2, X3>::def(const char*, F) [with F = F; W = osmium::NodeRefList; X1 = boost::noncopyable_::noncopyable; X2 = boost::python::detail::not_specified; X3 = boost::python::detail::not_specified]
     self& def(char const* name, F f)
           ^~~
/usr/include/boost/python/class.hpp:233:11: note:   template argument deduction/substitution failed:
In file included from lib/io.cc:5:0:
lib/osm.cc:173:111: note:   candidate expects 2 arguments, 3 provided
         .def("__getitem__", &osmium::NodeRefList::operator[], return_value_policy<reference_existing_object>())
                                                                                                               ^
In file included from /usr/include/boost/python.hpp:18:0,
                 from lib/io.cc:1:
/usr/include/boost/python/class.hpp:242:11: note: candidate: template<class A1, class A2> boost::python::class_<T, X1, X2, X3>::self& boost::python::class_<T, X1, X2, X3>::def(const char*, A1, const A2&) [with A1 = A1; A2 = A2; W = osmium::NodeRefList; X1 = boost::noncopyable_::noncopyable; X2 = boost::python::detail::not_specified; X3 = boost::python::detail::not_specified]
     self& def(char const* name, A1 a1, A2 const& a2)
           ^~~
/usr/include/boost/python/class.hpp:242:11: note:   template argument deduction/substitution failed:
In file included from lib/io.cc:5:0:
lib/osm.cc:173:111: note:   couldn't deduce template parameter 'A1'
         .def("__getitem__", &osmium::NodeRefList::operator[], return_value_policy<reference_existing_object>())
                                                                                                               ^
In file included from /usr/include/boost/python.hpp:18:0,
                 from lib/io.cc:1:
/usr/include/boost/python/class.hpp:249:11: note: candidate: template<class Fn, class A1, class A2> boost::python::class_<T, X1, X2, X3>::self& boost::python::class_<T, X1, X2, X3>::def(const char*, Fn, const A1&, const A2&) [with Fn = Fn; A1 = A1; A2 = A2; W = osmium::NodeRefList; X1 = boost::noncopyable_::noncopyable; X2 = boost::python::detail::not_specified; X3 = boost::python::detail::not_specified]
     self& def(char const* name, Fn fn, A1 const& a1, A2 const& a2)
           ^~~
/usr/include/boost/python/class.hpp:249:11: note:   template argument deduction/substitution failed:
In file included from lib/io.cc:5:0:
lib/osm.cc:173:111: note:   candidate expects 4 arguments, 3 provided
         .def("__getitem__", &osmium::NodeRefList::operator[], return_value_policy<reference_existing_object>())
                                                                                                               ^
In file included from /usr/include/boost/python.hpp:18:0,
                 from lib/io.cc:1:
/usr/include/boost/python/class.hpp:265:11: note: candidate: template<class Fn, class A1, class A2, class A3> boost::python::class_<T, X1, X2, X3>::self& boost::python::class_<T, X1, X2, X3>::def(const char*, Fn, const A1&, const A2&, const A3&) [with Fn = Fn; A1 = A1; A2 = A2; A3 = A3; W = osmium::NodeRefList; X1 = boost::noncopyable_::noncopyable; X2 = boost::python::detail::not_specified; X3 = boost::python::detail::not_specified]
     self& def(char const* name, Fn fn, A1 const& a1, A2 const& a2, A3 const& a3)
           ^~~
/usr/include/boost/python/class.hpp:265:11: note:   template argument deduction/substitution failed:
In file included from lib/io.cc:5:0:
lib/osm.cc:173:111: note:   candidate expects 5 arguments, 3 provided
         .def("__getitem__", &osmium::NodeRefList::operator[], return_value_policy<reference_existing_object>())
                                                                                                               ^
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
E: pybuild pybuild:276: build: plugin distutils failed with: exit code=1: /usr/bin/python setup.py build 
```
